apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: hello-chart
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
  selector:
    app: {{ .Values.name }}