name: Lint and Publish Chart
on:
  push:
    paths:
      - '**/Chart.yaml'
      - '**/values.yaml'
      - '**/k8s/**'
      - '.github/workflows/helm.yaml'
jobs:
  lint-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: 'v3.3.4'
      - name: Lint chart
        run: helm lint .
  publish-chart:
    needs: lint-chart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure Git
        run: |
          git config user.name "Emir Kerimberdiev"
          git config user.email "keremberdievemir43@gmail.com"
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.0.0
        env:
          CR_TOKEN: "${{ secrets.MY_TOKEN }}"